from django.urls import path
from .views import UserAccountViewSet
from rest_framework import routers

# Initialize a router and register your view set
router = routers.SimpleRouter()
router.register(r'', UserAccountViewSet, basename='user-account')

# Retrieve the list of URL patterns generated by the router
urlpatterns = router.urls
