# Generated by Django 4.2.10 on 2024-04-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='otp_expiration_time',
            field=models.IntegerField(default=0),
        ),
    ]
