# Generated by Django 4.2.10 on 2024-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='faculty',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
            preserve_default=False,
        ),
    ]
